language: node_js
node_js: stable 

# 只监听 source 分支的改动
branches:
  only:
    - source

#cache 缓存依赖，节省持续集成时间
cache:
  apt: true
  directories:
    - node_modules
    - themes
 
addons:
  ssh_known_hosts:
  - github.com
  - vensing.com

notifications:
  email:
    recipients:
      - vensing@foxmail.com
    on_success: never
    on_failure: never

# S: Build Lifecycle
install:
  - npm install
  - if [ ! -d "themes/Kratos-Rebirth" ]; then git clone -b custom https://github.com/vensing/Kratos-Rebirth.git themes/Kratos-Rebirth ; fi

before_script:
  # 解密 RSA 私钥并设置为本机 ssh 私钥
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in travis/travis.key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - export TZ='Asia/Shanghai'
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g

after_success:
  - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/ root@vensing.com:/hexo

after_script:
  - ./_travis.sh



