language: node_js
node_js: stable 

sudo: false

#cache
cache:
  apt: true
  directories:
    - "node_modules"
 
addons:
  ssh_known_hosts:
  - github.com
  - vensing.com

notifications:
  email:
    recipients:
      - vensing@foxmail.com
    on_success: never
    on_failure: never

# S: Build Lifecycle
install:
  - npm install
  - npm install less@2.7.3 --save-dev
#  - npm install gulp
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  # 解密 RSA 私钥并设置为本机 ssh 私钥
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv 
    -in travis/travis.key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - export TZ='Asia/Shanghai'
  - npm install gulp
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done
  - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/ root@www.vensing.com:/hexo

after_script:
  - ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - source
#env:
# global:
#   - GH_REF: github.com/vensing/vensing.github.io.git


