# Global
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: /images/favicon.ico
snow: false

# Top Menu
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/
  tools:
    submenu: true
    candifonts: /
    candidenty: /

label:
  index: <i class="fa fa-home"></i>&nbsp;首页
  archives: <i class="fa fa-file"></i>&nbsp;档案馆
  friends: <i class="fa fa-mars-double"></i>&nbsp;后宫团
  about: <i class="fa fa-rocket"></i>&nbsp;关于我
  tools:
    submenu: <i class="fa fa-flask"></i>&nbsp;实验室
    candifonts: 什么都没有
    candidenty: 即将到来

# Footer
qqg_link: 
contact:
  weibo: 
  tweibo: 
  mail: 
  twitter: https://twitter.com/youmohoshi
  facebook: 
  linkedin: 
  github: https://github.com/vensing
  
# Post Page
posts:
  show_cc: true
  donate: false
  share: true
  comments: true

# Disqus
disqus:
  shortname: vensing-com

# Widgets
sidebar: right
widgets:
- about
- category
- tagcloud
- posts
avatarUri: /images/avatar.jpg

# Code Highlight Themes: normal | night | night eighties | night blue | night bright
highlight_theme: night eighties